### ISSUE TITLE
Events ?

### ISSUE THREAD

**Issue by Jurigag** [Pentiado/angular-lazy-img#10]
On ie9 i have container which have other divs which have images - they all have to has same height - im using here matchHeight. What i want some event/directive or something which will occure when image is loaded and it can execute my function, but not this onSuccess function cuz i dont need it on every page to be executed.

**Comment by Pentiado** [comment]
Well, why not. Over the weekend I'll play with it

**Comment by Pentiado** [comment]
I added two events fired on $rootScope
lazyImg:success and lazyImg:error, each of them will pass as first param image
