### ISSUE TITLE
Using a scrollable container generated dynamically by controller

### ISSUE THREAD

**Issue by jup31** [Pentiado/angular-lazy-img#16]
Hello everybody,

I face an issue to work with the scrollable container as my container is generated using ng-view, it doesn't exist during the configuration step. Do you have any idea how I can solve this issue or is it dependent to the library ?

I had added a question on stackoverflow regarding this : [Stack question linked](http://stackoverflow.com/questions/36235757/configure-the-service-angular-lazy-img-with-a-dynamic-scrollable-container-gener)

Thanks in advance,
Julien

**Comment by jup31** [comment]
Soory I hadn't seen issue 4, I will test it.

**Comment by Pentiado** [comment]
Thanks for Pull Request!

**Comment by jup31** [comment]
No problem even if it doesn't solve fully my issue, the scrollable container is now good. The only issue is when scrolling quick the images aren't loaded. Did you know why it is not working ? I have look for scroll and touchMove event implemented in the code but I don't understand why image are only loaded if i scroll really slow and not fast.

**Comment by Pentiado** [comment]
https://github.com/Pentiado/angular-lazy-img/blob/master/src/angular-lazy-img-logic.js#L45
Function that checks images is wrapped in throttle for performance reasons. Maybe it's the culprit in your case?

I don't have time now to dive deep into this issue. Building start-up isn't an easy job. If you find the solution for your problem, feel free to send another pull request.
