### ISSUE TITLE
Image not displayed on fast scroll

### ISSUE THREAD

**Issue by jup31** [Pentiado/angular-lazy-img#18]
Please see here, image are not displayed if I scroll quick without touching the scrren at the end of the scroll : [Vidéo here](http://recordit.co/1owoyZghw6)

I'm working on an android phone, angular and cordova.

**Comment by bachvtuan** [comment]
It happened on normal scroll although I add "lazyImgContainer" as directive. some images are still loading.

**Comment by Pentiado** [comment]
Ok guys, two people are complaining about it. I need to take a look at this problem. This or next weekend I try to find some time.
