### ISSUE TITLE
make it work with filters

### ISSUE THREAD

**Issue by Mantish** [Pentiado/angular-lazy-img#2]
The plugin works fine except it doesn't work well with filters.
I'm not sure if it's possible

Example:
```
<li ng-repeat="product in products | filter:category">
    <img lazy-img="{{ product.mainImg }}" />
  </li>
```

**Comment by mbrammer** [comment]
Same problem here. @Mantish Can you provide a fix?

**Comment by mbrammer** [comment]
@Pentiado Just figured out that there is a newer codebase in your source than in the release folder. Is there a reason for that?
The newest version compiled from the source is working with filters. So you can use that @Mantish.

**Comment by Pentiado** [comment]
I probably just forgot to combine src or to commit it when I did it. I've built this plugin so long ago that I don't really remember. With my last commit all stuff from source got combined and landed in release
