### ISSUE TITLE
lazyImgContainer confusing

### ISSUE THREAD

**Issue by j-slvr** [Pentiado/angular-lazy-img#20]
plase note that the attribute to add to a container on a dynamic page is `lazy-img-container` (in kebab case) rather than the actual name `lazyImgContainer` (in camel case)

Even though this is convention in Angular, it still got me ;)

**Comment by canaltinova** [comment]
I'm not so experienced in angular and this got me too :)

**Comment by smcauliffe** [comment]
thanks for that!

**Comment by salilbajaj** [comment]
Can you write the sample code on how to use lazy-img-container

**Comment by Pentiado** [comment]
I updated readme and added demo/container-demo.html that shows how to use it so problem fixed : )
