### ISSUE TITLE
when state go back，image don't show

### ISSUE THREAD

**Issue by hcw2175** [Pentiado/angular-lazy-img#22]
i'm use ionic, when go back to list page like use code `$ionicHistory.goBack();`，all of the images don't show。i must to scroll the page, then the images will show，please help me.

my list page code:

```
<div class="cover" lazy-img="{{item.coverImg | img}}"></div>
```

the item is dynamic data of ajax request. 

use `$rootScope.$emit('lazyImg:refresh');` not work!!!

**Comment by Pentiado** [comment]
#30 should fix it. Let me know if you still have this problem though after a year you probably moved : )
