### ISSUE TITLE
Error LazyImgMagic is not a constructor in v1.4

### ISSUE THREAD

**Issue by geraintdong** [Pentiado/angular-lazy-img#37]
[This commit](https://github.com/Pentiado/angular-lazy-img/commit/06e61961455bc7cacf36c76bb82c5ed66c4a66c1) by @Pentiado causes an error when using this library
`LazyImgMagic is not a constructor`
Suggestion: The '$log' dependency injection should be placed before the 'LazyImgMagic'

**Comment by Pentiado** [comment]
Quick fixes are the source of evil.
