### ISSUE TITLE
Multiple lazy loaders in row not working

### ISSUE THREAD

**Issue by mich4s** [Pentiado/angular-lazy-img#39]
So i have this kind of code:

```
<div class="col-12 offer-box">
	<div class="offer-img tt1" lazy-img="css/images/transfery_na_lotniska.webp">
		<a href="#">
			<div class="desc-text">
				<h3>header</h3>

				<div class="hover-text">
					<p>text</p>
					<button class="see-more">więcej</button>
				</div>
			</div>
		</a>
	</div>
	<div class="desc-img">
		<h3>header</h3>

		<p>text</p>
		<a class="see-more" href="#">Zobacz więcej <i class="fa fa-angle-right"
													  aria-hidden="true"></i></a>
	</div>
</div>
<div class="col-12 offer-box">
	<div class="hidden-lg-down quote-text quote-left d-flex align-items-center">
		<div>
			<h5>header.</h5>

			<p>text.</p>
		</div>
	</div>
	<div class="offer-img tt1" lazy-img="css/images/wynajem_autokarow.webp">
		<a href="#">
			<div class="desc-text">
				<h3>header</h3>

				<div class="hover-text">
					<p>text</p>
					<button class="see-more">więcej</button>
				</div>
			</div>
		</a>
	</div>
	<div class="desc-img">
		<h3>header</h3>

		<p>text</p>
		<a class="see-more" href="#">Zobacz więcej <i class="fa fa-angle-right"
													  aria-hidden="true"></i></a>
	</div>
</div>
```

And few more. No matter how many of them i have, it'll only show last one.

In pevious part of document i have directive with this inside: 

```
<li class="news-list" ng-repeat="row in feed">
                                <div class="img-feed" lazy-img="{{row.image}}" style="background: no-repeat 50% / cover"></div>
                                <h4>{{row.title}}</h4>
                            </li>
```

and it's working 100% fine. Don't think webp format is issue here. I had all on png and wasn't working anyway.

What i noticed, that lazyimg is deployed for every corrupted image but will always show src of last one.

**Comment by jijishthomas** [comment]
i am having such an issue, lazy loader images are not shown anymore, it was working but now don't know what happened!

**Comment by SiddarthaAdusumalli** [comment]
Facing the same issue

**Comment by SidduSomething** [comment]
Faced the same issue

Using `scope:true` in this directive definition would solve the issue: https://github.com/Pentiado/angular-lazy-img/blob/7d282b52f3ebd65b955bbf7debb1a0e1494a5948/src/angular-lazy-img-directive.js#L26-L29
That will create a new non-isolated scope.

@mich4s in your second example, the `ng-repeat` is creating new scopes for each directive. Thats why it's working

**Comment by jijishthomas** [comment]
i have faced such an issue, and I solved it by updating angular version.

**Comment by mich4s** [comment]
Well it was quite long, and I've made my own simple directive, but still @SiddarthaAdusumalli answer is helpful.

**Comment by tah182** [comment]
Can we have this updated with the `scope: true` so there can be multiple directives on a page?
