### ISSUE TITLE
Set container in directive

### ISSUE THREAD

**Issue by alexnaldo** [Pentiado/angular-lazy-img#4]
If I have an image in a second page your code doesn't work because locates for 'window' or 'container' in the main page.

... in config code...

scrollable = document.querySelector('#scrollable')
 container: angular.element(scrollable)

**Comment by Pentiado** [comment]
Pull requests are welcome : )

**Comment by Jurigag** [comment]
+1 Anyone have solution ?

**Comment by Pentiado** [comment]
Tomorrow I start my vacation, then I'll jump into this issue : )

**Comment by Pentiado** [comment]
I added a directive "lazyImgContainer" which when added to some element as attribute will trigger on scroll "checkImages" the same way as window (or container if set in provider)

**Comment by Jurigag** [comment]
Nice, i will test it tomorrow and provide some info :D

**Comment by Jurigag** [comment]
How is it working exactly ? I have div with style like and added directive lazy-img-container:

overflow-y:scroll
height:400px

and in there ng-repeat with div where inside are images, but its not working

**Comment by rictorres** [comment]
Doesn't work for me either. Tried passing `container` inside the `options` object and also attaching `lazy-img-container` to the scrollable element.

I think this should be reopened :)

**Comment by rictorres** [comment]
Bower registry has an old version of this module: https://github.com/Pentiado/angular-lazy-img/issues/8

```
bower install --save angular-lazy-img#fa48333273f9e
```
or
```
bower install --save angular-lazy-img#master
```

will work for now.

**Comment by Pentiado** [comment]
Yes, sorry guys I forgot about publishing tag. Now it should be working.
