### ISSUE TITLE
Helper to call check manually

### ISSUE THREAD

**Issue by mbrammer** [Pentiado/angular-lazy-img#5]
Hello,

could you provide a helper or something to trigger the image check manually?
My problem: I have an image slider which will show images in an `overflow: hidden` wrapper, when clicking on an arrow. But the images won't be visible unless I scroll the entire page up or down.
So it would be nice if there was a function I could call on every click on the arrow.

**Comment by Pentiado** [comment]
Hey! As soon a things cool down at job I might jump back into Open Source projects but it might be a week or two. In meantime I'm open for pull requests!
